version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 8000:8000

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile